# In a real cluste obviously either encrypted or not in git.
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
data:
  age.agekey: IyBjcmVhdGVkOiAyMDI0LTA0LTE3VDEyOjMzOjI1KzAyOjAwCiMgcHVibGljIGtleTogYWdlMWxjZnNhbTVmZHNucjBsM2ZmMGt2bnFmeDQ1MGhjanIycWc2Y3l4OHFza2p0NHVtNzhkMnNsdzJjbWcKQUdFLVNFQ1JFVC1LRVktMTRRTEpVTTY2VE5WOFhVVEVIRkRLSFo1VlFISzZNTEdUTkpGQ1FaMlowWEtXOEQ4RUg4WVNBQUxHRTUK
